apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-sample-flask
  labels: 
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-sample-flask
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.port: "8081"
    #tanzu.app.live.view.application.flavours: spring-boot
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/trevorputbrese/sample-flask.git
      ref:
        branch: main

